# Generated by Django 5.2.15 on 2026-06-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_box_price', models.DecimalField(decimal_places=2, default=600, max_digits=10, verbose_name='سعر البوكس الاساسي للحكومي')),
                ('private_college_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='زيادة الاهلية عن الحكومي')),
                ('lab_coat_price', models.DecimalField(decimal_places=2, default=200, max_digits=10, verbose_name='سعر اللاب كوت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='اخر تحديث')),
            ],
            options={
                'verbose_name': 'اعدادات الاسعار',
                'verbose_name_plural': 'اعدادات الاسعار',
            },
        ),
    ]
