# Generated by Django 5.2.15 on 2026-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_pricingsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='college_type',
        ),
        migrations.RemoveField(
            model_name='pricingsettings',
            name='private_college_extra',
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='base_box_price',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10, verbose_name='سعر البوكس الاساسي'),
        ),
    ]
