# Generated by Django 5.2.13 on 2026-07-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_order_college_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='college_type',
            field=models.CharField(choices=[('government', 'حكومي'), ('private', 'اهلية')], default='government', max_length=20, verbose_name='نوع الكلية'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='private_college_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='زيادة الاهلية عن الحكومي'),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='base_box_price',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10, verbose_name='سعر البوكس الاساسي للحكومي'),
        ),
    ]
